### ISSUE TITLE
ServerID should not be a new column in pg_proc

### ISSUE THREAD

**Issue by davidfetter** [davidfetter/postgresql_projects#3]
Instead, do the following:

- Add a bool proisforeign to pg_proc
- Create a new table pg_foreign_proc, which is conceptually:
```sql
CREATE TABLE pg_foreign_proc (
    fproname name,
    fproc oid UNIQUE NOT NULL REFERENCES pg_proc(oid),
    fserver oid NOT NULL REFERENCES pg_foreign_server(oid)
    fprooptions TEXT[] /* Contains things like foreign schema, foreign function name, etc. */
);
```

There also needs to be a pg_depend entry created for each foreign function along the lines of
```
10:54 <MatheusOl> davidfetter: e.g. classid = 'pg_proc'::regclass::oid, objid = pg_proc.oid of the function, objsubid = 0, refclassid = 'pg_foreign_server'::regclass::oid, refobjid = pg_foreign_server.oid of the server, refobjsubid = 0, deptype = 'n'
```

**Comment by coreyhuinker** [comment]
I think we can do it that way. Share your or (Mathueus01's) thoughts as to the underlying reasons?

**Comment by davidfetter** [comment]
A couple of things:

- Other things like FOREIGN TABLE are done this way
- It seems really weird to have every function in pg_proc to get something large when nothing else will ever use it. A boolean seems about the most disturbance to pg_proc I'd want to add.

The dependency stuff is maybe just further work in the mechanism, but I wanted to capture the "how" somewhere. Maybe that google doc would be a better place.

**Comment by coreyhuinker** [comment]
I agree with regards to conforming to FOREIGN TABLE patterns.
I agree it's a big change to pg_proc.h, a file not resilient when it comes to big changes.
Given that, do we need a column at all? Isn't having selected language = sqlmed enough? A row with lang sqlmed could never be anything other than proisforeign = true, and any other language is (at least currently) is always proisforeign = false.
I'm fine with using this for now, it has a conversation format that is easy to follow and I'll capture it into the google doc anyway.
